# Netflix Recommendation System

## Notebook 1 : Data Cleaning

Author : Bishal Gurung

Dataset : Netflix Movies and TV Shows

Goal:
Prepare the raw dataset for analysis and machine learning.

1. Import Libraries

2. Load Dataset

3. Dataset Overview

4. Missing Values

5. Duplicate Values

6. Data Type Conversion and Creates new features

7. Save Clean Dataset

# 1 Import Required Libraries

In [16]:
import pandas as pd
import numpy as np

# 2 Load Dataset

In [17]:
df = pd.read_csv("../data/netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

# 3. Data Overview

In [18]:
df.shape

(8807, 12)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 3.9 MB

In [20]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

# 4. Missing Values

In [21]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [22]:
# Fill missing text values
for col in ["director", "cast", "country"]:
    df[col] = df[col].fillna("Unknown")

# Fill missing categorical values with most common value
for col in ["rating", "duration", "date_added"]:
    df[col] = df[col].fillna(df[col].mode()[0])

# Verify missing values
print(df.isnull().sum())

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

# 5. Duplicates Values

In [23]:
df.duplicated().sum()

np.int64(0)

# 6. Data Type Conversion and Creates new features

In [24]:
# Convert date_added into datetime format
# errors='coerce' converts invalid dates into NaT instead of crashing

df["date_added"] = pd.to_datetime(
    df["date_added"].astype(str).str.strip(),
    errors="coerce"
)

# Fill any failed date conversions with the most common valid date
df["date_added"] = df["date_added"].fillna(df["date_added"].mode()[0])

# Extract year and month added
df["year_added"] = df["date_added"].dt.year
df["month_added"] = df["date_added"].dt.month

df[["date_added", "year_added", "month_added"]].head()

  date_added  year_added  month_added
0 2021-09-25        2021            9
1 2021-09-24        2021            9
2 2021-09-24        2021            9
3 2021-09-24        2021            9
4 2021-09-24        2021            9

# 7. Save Clean Dataset

In [25]:
df.to_csv(
    "../data/processed/netflix_cleaned.csv",
    index=False
)

## Conclusion

In this notebook we

✔ Loaded dataset

✔ Cleaned missing values

✔ Removed duplicates

✔ Saved cleaned dataset