# Netflix Recommendation System

# Notebook 3: Feature Engineering

## Author
Bishal Gurung

## Objective

Feature engineering transforms raw data into meaningful numerical features that machine learning algorithms can learn from.

### Goals

- Load cleaned dataset
- Create text feature
- Convert text into numerical vectors using TF-IDF
- Encode target variable
- Split the data into training and testing sets
- Save processed features

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("../data/processed/netflix_cleaned.csv")

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9

We combine title, genre, and description into one text column. This gives the ML model more information.

In [3]:
df["text"] = (
    df["title"].astype(str)
    + " "
    + df["listed_in"].astype(str)
    + " "
    + df["description"].astype(str)
)

# Convert target labels into numbers
# Movie = 0, TV Show = 1

df["target"] = df["type"].map({
    "Movie": 0,
    "TV Show": 1
})

df[["type", "target", "text"]].head()

      type  target                                               text
0    Movie       0  Dick Johnson Is Dead Documentaries As her fath...
1  TV Show       1  Blood & Water International TV Shows, TV Drama...
2  TV Show       1  Ganglands Crime TV Shows, International TV Sho...
3  TV Show       1  Jailbirds New Orleans Docuseries, Reality TV F...
4  TV Show       1  Kota Factory International TV Shows, Romantic ...

# Train-Test Split
We split data into training and testing sets. This helps us check whether the model performs well on unseen data.

In [4]:
from sklearn.model_selection import train_test_split

X = df["text"]
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training size:", X_train.shape)
print("Testing size:", X_test.shape)

Training size: (7045,)
Testing size: (1762,)

# TF-IDF Vectorization
Machine learning models cannot understand raw text. TF-IDF converts text into numerical features.

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=5000
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Train TF-IDF shape:", X_train_tfidf.shape)
print("Test TF-IDF shape:", X_test_tfidf.shape)

Train TF-IDF shape: (7045, 5000)
Test TF-IDF shape: (1762, 5000)

In [7]:
import joblib

joblib.dump(
    tfidf,
    "../models/Final_Model/tfidf_vectorizer.pkl"
)

print("TF-IDF Vectorizer Saved Successfully")

TF-IDF Vectorizer Saved Successfully

# Conclusion

In this notebook, we:

- Loaded the cleaned dataset
- Created a text feature
- Encoded the target variable
- Applied TF-IDF vectorization
- Split the dataset into training and testing sets
- Saved the TF-IDF vectorizer for future use

The processed data is now ready for machine learning model training.